#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # Directory where this script exists.
__root="$(cd "$(dirname "${__dir}")" && pwd)"         # Root directory of project.

BRING_VERSION=${BRING_VERSION:-"v0.0.0-test"}
TIME_BUILD=$(date --rfc-3339=seconds)
GIT_REV=$(git rev-parse HEAD)
GIT_DIRTY=$(git status --porcelain | read -t 0 && echo "true" || echo "false")

cd "$__root"

(cat | tee ./cmd/version.g.go) <<EOL
// Code generated by scripts/gen-version-file.sh; DO NOT EDIT.
package cmd

func init(){
	b := &_buildInfo
	b.Version   = "$BRING_VERSION"
	b.TimeBuild = "$TIME_BUILD"
	b.GitRev    = "$GIT_REV"
	b.GitDirty  = $GIT_DIRTY
}
EOL

