name: release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: Name of the version to release
        required: false
        default: "v0.0.0-test"
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        run: |
          go generate ./...
          cat ./cmd/version.g.go
        env:
          BRING_VERSION: ${{ github.event_name != 'workflow_dispatch' && github.ref_name || inputs.version }}

      - name: Image meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/lesomnus/bring:edge
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/lesomnus/bring:edge
          push: true
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
